export BLUE="%%{F#4d8ddb}"
export GREEN="%%{F#42d6b9}"
export RED="%%{F#db4d4d}"
export YELLOW="%%{F#dbc14d}"
export DARK="%%{F#262626}"
export LIGHT="%%{F#dbdbdb}"
export PURPLE="%%{F#ad39cb}"
export ORANGE="%%{F#ff9838}"
export GRAY="%%{F#555555}"

export GREEN_S="%{F#42d6b9}"
export PURPLE_S="%{F#ad39cb}"

export PROGRESS_OFF="%{u#545758}"
export PROGRESS_MEM="%{u#42d6b9}"
export PROGRESS_SWAP="%{u#ad39cb}"
export PROGRESS_BLUE="%{u#4d8ddb}"

export BAR_RED="%%{u#db4d4d}"
export BAR_GREEN="%%{u#42d6b9}"
export BAR_BLUE="%%{u#4d8ddb}"
export BAR_ORANGE="%%{u#ff9838}"
export BAR_PURPLE="%%{U#ad39cb}"
export BAR_GRAY="%%{u#a6a6a6}"
export BAR_DARK="%%{u#262626}"

export NO_F_COLOR="%%{F-}"
export NO_B_COLOR="%%{B-}"
export NO_BAR_COLOR="%%{u-}"
export NO_BAR="%%{-u}"
